export { default as play_icon } from '../utils/play-button.png'
export { default as trash_icon } from '../utils/trash-outline.svg'
export { default as pause_icon } from '../utils/pause-outline.svg'
export { default as settings_icon } from '../utils/settings-outline.svg'
export { default as user_icon } from '../utils/person-outline.svg'
export { default as logo } from '../utils/logo.png'
export { default as logo2 } from '../utils/logo.svg'
export { default as tick_icon } from '../utils/checkmark-outline.svg'
export { default as cross_icon } from '../utils/close-outline.svg'
export { default as filter_icon } from '../utils/filter-outline.svg'
export { default as upload_icon } from '../utils/cloud-upload-outline.svg'
export { default as arrow_down_icon } from '../utils/chevron-down-outline.svg'
export { default as arrow_up_icon } from '../utils/chevron-up-outline.svg'
export { default as flag_icon } from '../utils/flag-outline.svg'
export { default as help_icon } from '../utils/help-outline.svg'
export { default as stats_icon } from '../utils/stats-chart-outline.svg'
export { default as search_icon } from '../utils/search-outline.svg'
export { default as plot_icon } from '../utils/plot_icon.png'
export { default as back_icon } from '../utils/arrow-back-outline.svg'
export { default as kmeans } from '../utils/cluster.png'
export { default as no_kmeans } from '../utils/no_cluster.png'
export { default as swap_icon } from '../utils/swap.png'
export { default as grid_icon } from '../utils/grid.png'
export { default as wave_icon } from '../utils/waveform.png'
export { default as training_icon } from '../utils/brain.png' //<a href="https://www.flaticon.com/free-icons/machine-learning" title="machine learning icons">Machine learning icons created by VectorPortal - Flaticon</a>
export { default as cacophony_logo } from '../utils/cacophony.png'
export { default as pf2050_logo } from '../utils/pf2050.png'
export { default as canterbury_logo } from '../utils/canterbury.png'
export { default as listening_lab } from '../utils/listening_lab.ico'
export { default as listening_lab_transparent } from '../utils/Transparent Logo.svg'
export { default as listening_lab_web } from '../utils/Listening Lab Web.png'
export { default as test_video } from '../utils/test.mp4'
